dist: xenial
language: php
compiler:
    - gcc
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4
services:
    - docker
jobs:
    include:
        - php: 7.4
          env:
            - LIBRDKAFKA_VERSION=v1.2.2
            - MEMORY_CHECK=1
          stage: master_test
          name: Master Test
          addons:
              apt:
                  packages:
                      - valgrind
        - stage: test
          env:
            - LIBRDKAFKA_VERSION=0.11.x
        - env:
            - LIBRDKAFKA_VERSION=v1.0.1
        - env:
            - LIBRDKAFKA_VERSION=v1.1.0
        - env:
            - LIBRDKAFKA_VERSION=v1.2.2
        - env:
            - LIBRDKAFKA_VERSION=master
env:
    global:
        - TEST_KAFKA_BROKERS=kafka:9092
        - TEST_KAFKA_BROKER_VERSION=2.3
        - LIBRDKAFKA_REPOSITORY_URL=https://github.com/edenhill/librdkafka.git
        - LIBRDKAFKA_VERSION=v1.2.2
before_install:
    - |
      # Start Kafka and install an up-to-date librdkafka
      docker network create kafka_network
      docker pull wurstmeister/zookeeper:3.4.6
      docker run -d --network kafka_network --name zookeeper wurstmeister/zookeeper:3.4.6
      docker pull wurstmeister/kafka:2.12-2.3.1
      docker run -d -p 9092:9092 --network kafka_network -e "KAFKA_AUTO_CREATE_TOPICS_ENABLE=true" -e "KAFKA_CREATE_TOPICS=test-topic:1:1:compact" -e "KAFKA_ADVERTISED_HOST_NAME=kafka" -e "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181" -e "KAFKA_ADVERTISED_PORT=9092" --name kafka wurstmeister/kafka:2.12-2.3.1
      export KAFKA_BROKER=kafka:9092
      sudo sh -c 'echo "\n127.0.0.1  kafka\n" >> /etc/hosts'

      mkdir /tmp/librdkafka
      cd /tmp/librdkafka
      git clone --depth 1 --branch "${LIBRDKAFKA_VERSION:-v1.2.2}" "${LIBRDKAFKA_REPOSITORY_URL:-https://github.com/edenhill/librdkafka.git}" .
      ./configure && make && sudo make install
      cd -
    - set -e
install:
    - sudo ldconfig
    - echo "extension = $(pwd)/modules/rdkafka.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - phpenv config-rm xdebug.ini || true
    - phpize
    - CFLAGS='-Werror=implicit-function-declaration' ./configure && make
script:
    - export PATH=$TRAVIS_BUILD_DIR/.travis:$PATH
    ### Issues with environmental variables causes this copy to be required
    - cp tests/test_env.php.sample tests/test_env.php
    - PHP=$(which php)
    - REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE="$PHP" "$PHP" run-tests.php -q --show-diff
